feat: Add invert option
bahmutov/cypress-select-tests pull request #76
Opened 2020-01-17 01:40 UTC by untidy-hair

closes #75 

This makes invert option available. Please check the updated README for the usage.

I have been tempted to reduce duplications of the code when we have console log output sentences and negations are only changes.
I was trying a little bit the code got uglier than this. 

Any suggestion would be welcome!
(Also, lmk about the test, if necessary. I could not figure out.)

2020-01-20 05:54 UTC, untidy-hair commented
Any thoughts? @bahmutov

2020-01-21 14:28 UTC, bahmutov requested changes
Please add a test to make sure the invert option is working. You can see how the tests are set up in the current repo in file https://github.com/bahmutov/cypress-select-tests/blob/master/test/spec.js - each unit test runs Cypress using NPM module API and a different plugins file. The plugins file passes options, in your case it would have the invert option.

2020-01-21 17:28 UTC, untidy-hair commented
I took some time to look at the codebase as well as tests and I think I have better understanding now. I still need some time to get the complete understanding but I'll give it a shot!

2020-01-25 00:34 UTC, untidy-hair commented
@bahmutov I added tests and snapshots I added match what I expected! Let me know if my tests are not following the conventions here.

2020-01-28 20:44 UTC, bahmutov approved these changes
Looks very good, merging

2020-01-28 20:44 UTC, merged

2020-01-28 20:48 UTC, bahmutov commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- `npm package (@latest dist-tag)`
- [GitHub release](https://github.com/bahmutov/cypress-select-tests/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2020-01-28 22:33 UTC, untidy-hair commented
Thanks!